---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: Install Command Line Tools
      include_role:
        name: elliotweiser.osx-command-line-tools

    - name: Install Homebrew
      include_role:
        name: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - name: Install dotfiles
      include_role:
        name: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

    - name: Install Mac App Store Applications
      include_role:
        name: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    
    - name: Accept XCode Terms
      ansible.builtin.command: sudo xcodebuild -license accept
      when: accept_xcode_license

    - name: Configure Dock
      include_role:
        name: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - import_tasks: tasks/vscode.yml
      when: configure_vscode
      tags: ['vs-code']

    - import_tasks: tasks/add-applications-dock.yml
      when: add_applications_to_dock
      tags: ['dock']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
